Feat/first chapter/first exercise
miguelmadera50/codesessions_cracking pull request #5
Opened 2018-02-17 22:30 UTC by sirgalleto

2018-02-17 22:40 UTC, miguelmadera50 submitted a review, later dismissed
😘

2018-02-17 22:44 UTC, hevela requested changes

2018-02-17 22:44 UTC, hevela commented on sirgalleto/chapter-1/first-problem.js
> +      if (string[index] === string[secondaryIndex]) {
this code does not work as intended. this only checks the case in which the letter being evaluated is equal to the previous one.

2018-03-03 22:14 UTC, miguelmadera50 requested changes
Use updated test file for tests also.

2023-03-07 05:02 UTC, closed without merging